[package]
name = "robonames"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.4.0"
num = "0.4.1"
ring = "0.17.7"
sha2 = "0.10.1"
